# Generated by Django 5.0 on 2024-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='upload',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
