# Generated by Django 5.0 on 2024-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_upload_uploaded_at_upload_wav_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
